iceberg/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from app.views import home, addEvent
from iceberg import settings

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', home, name='home'),
    url(r'^addevent/$', addEvent, name='addevent'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name="logout"),

    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    )

app/models.py
from django.db import models
from django.contrib.auth.models import User


class Event(models.Model):
    name = models.CharField(max_length=100)
    start_day = models.DateField()
    start_time = models.CharField(blank=True, default='09:00:00', max_length=10)
    description = models.TextField(max_length=300, blank=True)
    user = models.ForeignKey(User)

    def __unicode__(self):
        return self.name

app/forms.py
from django import forms
from models import Event


class EventForm(forms.ModelForm):

    class Meta:
        model = Event
        fields = ['name', 'start_day', 'start_time', 'description']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title'}),
            'start_day': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Day'}),
            'start_time': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Time'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description'}),
        }

app/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.core.context_processors import csrf
from django.shortcuts import render_to_response, get_object_or_404
from forms import EventForm
from models import Event
from django.contrib.auth.models import User


def home(request):

    args={}
    args.update(csrf(request))

    if request.user.is_authenticated():

        e = Event.objects.filter(user=request.user)
        args.update({'e': e})
        template = 'cal.html'

    else:

        username = password = state = ''
        if request.POST:
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse("home"))
                else:
                    state = "Your account is not active, please contact the support."
            else:
                state = "Your username or password were incorrect."

        args.update({'state': state})
        template = 'index.html'

    context = RequestContext(request)
    return render_to_response(template, args, context_instance=context)


def addEvent(request):

    args = {}
    args.update(csrf(request))

    u = get_object_or_404(User, username=request.user)
    status = 0

    #making some fun stuff-----------------------------------------------
    if request.POST:
        form = EventForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = u
            form.save()
            status = 1

            return HttpResponseRedirect(reverse('home'))
    else:
        form = EventForm()
        status = 0

    #packing bags and fly--------------------------------------------------
    args.update({'status': status, 'form': form})
    template = 'addevent.html'
    context = RequestContext(request)
    return render_to_response(template, args, context_instance=context)

app/templates/addevent.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <link href="{{STATIC_URL}}css/bootstrap.min.css" rel="stylesheet">
    <link type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.6/themes/redmond/jquery-ui.css" rel="Stylesheet" />
<script language="javascript" type="text/javascript" src="{{STATIC_URL}}js/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.6/jquery-ui.min.js"></script>
</head>
<body>
    <div class="container">
        <h1>Add new event</h1>
        <div class="panel panel-default">
            <div class="panel-body">
                <form role="form" action="" method="POST">
                    {% csrf_token %}
                    {% for f in form %}
                        <div class="form-group">{{ f }}</div>
                    {% endfor %}
                        <div class="form-group"><input value="Submit" type="submit" class="btn btn-default"/></div>
                </form>
            </div>
        </div>
    </div>
    <script type="text/javascript">
      $(function(){
        $("#id_start_day").datepicker();
        $("#id_start_day").timepicker();
      });
    </script>
</body>
</html>

app/templates/cal.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- <link rel="icon" href="../../favicon.ico"> -->

    <title>User Page</title>

    <!-- Bootstrap core CSS -->
    <link href="{{STATIC_URL}}css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{STATIC_URL}}css/dashboard.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href='{{STATIC_URL}}fullcalendar/fullcalendar.css' rel='stylesheet' />
  <link href='{{STATIC_URL}}fullcalendar/fullcalendar.print.css' rel='stylesheet' media='print' />
  <script src='{{STATIC_URL}}fullcalendar/lib/moment.min.js'></script>
  <script src='{{STATIC_URL}}js/jquery.min.js'></script>
  <script src='{{STATIC_URL}}fullcalendar/fullcalendar.min.js'></script>
  <script>

  $(document).ready(function() {


    $('#calendar').fullCalendar({
      defaultDate: '2014-11-27',
      editable: false,
      eventLimit: true, // allow "more" link when too many events
      events: [
        {% for ee in e %}
        {
          title: '{{ee.name}}',
          start: '{{ee.start_day}}'
        },
        {% endfor %}
      ]
    });

  });

</script>
<style>

  body {
    margin: 40px 10px;
    padding: 0;
    font-family: "Lucida Grande",Helvetica,Arial,Verdana,sans-serif;
    font-size: 14px;
  }

  #calendar {
    max-width: 900px;
    margin: 0 auto;
  }

</style>

  </head>

  <body>





  </body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Iceberg</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'addevent' %}">Add event</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
          </ul>

        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#">Schedule</a></li>
            <li><a href="#">Reports</a></li>
            <li><a href="#">Analytics</a></li>
            <li><a href="#">Export</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="header">Event Planner</h2>
            <div id="calendar"></div>

          <h2 class="sub-header">Event List</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1,001</td>
                  <td>Lorem</td>
                  <td>ipsum</td>
                  <td>dolor</td>
                  <td>sit</td>
                </tr>
                <tr>
                  <td>1,002</td>
                  <td>amet</td>
                  <td>consectetur</td>
                  <td>adipiscing</td>
                  <td>elit</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>Integer</td>
                  <td>nec</td>
                  <td>odio</td>
                  <td>Praesent</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>libero</td>
                  <td>Sed</td>
                  <td>cursus</td>
                  <td>ante</td>
                </tr>
                <tr>
                  <td>1,004</td>
                  <td>dapibus</td>
                  <td>diam</td>
                  <td>Sed</td>
                  <td>nisi</td>
                </tr>
                <tr>
                  <td>1,005</td>
                  <td>Nulla</td>
                  <td>quis</td>
                  <td>sem</td>
                  <td>at</td>
                </tr>
                <tr>
                  <td>1,006</td>
                  <td>nibh</td>
                  <td>elementum</td>
                  <td>imperdiet</td>
                  <td>Duis</td>
                </tr>
                <tr>
                  <td>1,007</td>
                  <td>sagittis</td>
                  <td>ipsum</td>
                  <td>Praesent</td>
                  <td>mauris</td>
                </tr>
                <tr>
                  <td>1,008</td>
                  <td>Fusce</td>
                  <td>nec</td>
                  <td>tellus</td>
                  <td>sed</td>
                </tr>
                <tr>
                  <td>1,009</td>
                  <td>augue</td>
                  <td>semper</td>
                  <td>porta</td>
                  <td>Mauris</td>
                </tr>
                <tr>
                  <td>1,010</td>
                  <td>massa</td>
                  <td>Vestibulum</td>
                  <td>lacinia</td>
                  <td>arcu</td>
                </tr>
                <tr>
                  <td>1,011</td>
                  <td>eget</td>
                  <td>nulla</td>
                  <td>Class</td>
                  <td>aptent</td>
                </tr>
                <tr>
                  <td>1,012</td>
                  <td>taciti</td>
                  <td>sociosqu</td>
                  <td>ad</td>
                  <td>litora</td>
                </tr>
                <tr>
                  <td>1,013</td>
                  <td>torquent</td>
                  <td>per</td>
                  <td>conubia</td>
                  <td>nostra</td>
                </tr>
                <tr>
                  <td>1,014</td>
                  <td>per</td>
                  <td>inceptos</td>
                  <td>himenaeos</td>
                  <td>Curabitur</td>
                </tr>
                <tr>
                  <td>1,015</td>
                  <td>sodales</td>
                  <td>ligula</td>
                  <td>in</td>
                  <td>libero</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- // <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script> -->
    <script src="{{STATIC_URL}}js/bootstrap.min.js"></script>


  </body>

</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>IceBerg</title>
    <link href="{{STATIC_URL}}css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% if not user.is_authenticated %}
<div class="container" style="width: 300px">

    <form class="form-signin" role="form" method="post" action="?">
        {% csrf_token %}
        <h2 class="form-signin-heading">Please sign in</h2>
        <input type="username" class="form-control" placeholder="username" name="username" required autofocus>
        <input type="password" class="form-control" placeholder="Password" name="password" required>
        <div class="checkbox">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        <p id="errHere" style="color:#ff0000;"></p>
    </form>
    {% if state %}
    <script>
        document.getElementById("errHere").innerHTML = "{{state}}";
    </script>
    {% endif %}

</div>
{% else %}
    <b>Hello and enjoy!</b> <a href="{% url 'logout' %}">Logout</a>
{% endif %}
<script src="{{STATIC_URL}}js/jquery.min.js"></script>
<script src="{{STATIC_URL}}js/bootstrap.min.js"></script>
</body>
</html>